using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Practice_3
{
    public partial class Showinfo : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            string base64 = Convert.ToBase64String(File.ReadAllBytes(@"E:\Practice_3\js.jpg"));
            TextBox7.Text = base64;

            var image = System.Drawing.Image.FromStream(new MemoryStream(Convert.FromBase64String(base64)));
            image.Save(@"E:\Practice_3\new.jpg", ImageFormat.Jpeg);
        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            Panel1.Visible = true;
        }

        protected void Button2_Click(object sender, EventArgs e)
        {
            SqlDataSource2.Insert();
            GridView2.DataBind();
            TextBox1.Text = "";
            TextBox2.Text = "";
            TextBox3.Text = "";
            Panel1.Visible=false;
        }

        protected void Button3_Click(object sender, EventArgs e)
        {
            TextBox1.Text = "";
            TextBox2.Text = "";
            TextBox3.Text = "";
            Panel1.Visible = false;
        }

        protected void Button4_Click(object sender, EventArgs e)
        {
            if (Button4.Text == "Редактировать заказы")
            {
                GridView2.AutoGenerateEditButton = true;
                Button4.Text = "Закончить редактирование";
            }
            else
            {
                GridView2.AutoGenerateEditButton = false;
                Button4.Text = "Редактировать заказы";
            }
        }

        protected void Button5_Click(object sender, EventArgs e)
        {
            if (Button5.Text == "Удалить заказ")
            {
                GridView2.AutoGenerateDeleteButton = true;
                Button5.Text = "Закончить удаление";
            }
            else
            {
                GridView2.AutoGenerateDeleteButton = false;
                Button5.Text = "Удалить заказ";
            }
        }

        protected void Button6_Click(object sender, EventArgs e)
        {
            Panel2.Visible = true;
        }

        protected void Button7_Click(object sender, EventArgs e)
        {
            SqlDataSource1.Insert();
            GridView1.DataBind();
            TextBox4.Text = "";
            TextBox5.Text = "";
            TextBox6.Text = "";
            Panel2.Visible=false;
        }

        protected void Button8_Click(object sender, EventArgs e)
        {
            TextBox4.Text = "";
            TextBox5.Text = "";
            TextBox6.Text = "";
            Panel2.Visible = false;
        }

        protected void Button9_Click(object sender, EventArgs e)
        {
            if (Button9.Text == "Редактировать заказчиков")
            {
                GridView1.AutoGenerateEditButton = true;
                Button9.Text = "Закончить редактирование";
            }
            else
            {
                GridView1.AutoGenerateEditButton = false;
                Button9.Text = "Редактировать заказчиков";
            }
        }

        protected void Button10_Click(object sender, EventArgs e)
        {
            if (Button10.Text == "Удалить заказчиков")
            {
                GridView1.AutoGenerateDeleteButton = true;
                Button10.Text = "Закончить удаление";
            }
            else
            {
                GridView1.AutoGenerateDeleteButton = false;
                Button10.Text = "Удалить заказчиков";
            }
        }
    }
}